// mobile/src/pages/Login.tsx
import { useState } from 'react';
import { Form, Input, Button, Toast } from 'antd-mobile';
import { useNavigate } from 'react-router-dom';
import { login as loginApi } from '@/api/auth';
import { useAuthStore } from '@/stores/authStore';

export default function Login() {
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const { setTokens, setUser } = useAuthStore();

  const onFinish = async (values: { username: string; password: string }) => {
    setLoading(true);
    try {
      const { data: res } = await loginApi(values.username, values.password);
      if (res.code !== 0) {
        Toast.show({ content: res.data?.toString() || '登录失败', icon: 'fail' });
        return;
      }
      setTokens(res.data.access_token, res.data.refresh_token);
      setUser(res.data.user);
      Toast.show({ content: '登录成功', icon: 'success' });
      navigate('/mobile', { replace: true });
    } catch (err: unknown) {
      const message =
        (err as { response?: { data?: { message?: string } } })?.response?.data?.message ||
        '网络错误';
      Toast.show({ content: message, icon: 'fail' });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        padding: '0 24px',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      }}
    >
      <div
        style={{
          background: '#fff',
          borderRadius: 16,
          padding: '40px 24px',
          boxShadow: '0 8px 32px rgba(0,0,0,0.15)',
        }}
      >
        <h1 style={{ textAlign: 'center', marginBottom: 8, fontSize: 24 }}>
          Home Guardian
        </h1>
        <p style={{ textAlign: 'center', color: '#999', marginBottom: 32, fontSize: 14 }}>
          智能家居控制面板
        </p>

        <Form onFinish={onFinish} footer={
          <Button block type="submit" color="primary" size="large" loading={loading}>
            登录
          </Button>
        }>
          <Form.Item name="username" rules={[{ required: true, message: '请输入用户名' }]}>
            <Input placeholder="用户名" clearable autoComplete="username" />
          </Form.Item>
          <Form.Item name="password" rules={[{ required: true, message: '请输入密码' }]}>
            <Input type="password" placeholder="密码" clearable autoComplete="current-password" />
          </Form.Item>
        </Form>
      </div>
    </div>
  );
}

// frontend/src/views/Login.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import {
  NCard,
  NForm,
  NFormItem,
  NInput,
  NButton,
  NSpace,
  useMessage,
  type FormRules,
  type FormInst,
} from 'naive-ui'
import { useAuthStore } from '@/stores/auth'
import { loginApi } from '@/api/auth'
import { useAppStore } from '@/stores/app'

const router = useRouter()
const message = useMessage()
const authStore = useAuthStore()
const appStore = useAppStore()

const formRef = ref<FormInst | null>(null)
const loading = ref(false)

const form = reactive({
  username: '',
  password: '',
})

const rules: FormRules = {
  username: { required: true, message: '请输入用户名', trigger: 'blur' },
  password: { required: true, message: '请输入密码', trigger: 'blur' },
}

async function handleLogin() {
  try {
    await formRef.value?.validate()
  } catch {
    return
  }

  loading.value = true
  try {
    const res = await loginApi(form)
    authStore.setTokens(res.data.access_token, res.data.refresh_token)
    message.success('登录成功')
    router.push('/')
  } catch (err: any) {
    message.error(err.response?.data?.message || '登录失败')
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div
    class="min-h-screen flex items-center justify-center p-4"
    :style="{ background: appStore.isDark ? '#101014' : '#f0f2f5' }"
  >
    <div class="w-full max-w-[400px]">
      <div class="text-center mb-8">
        <div class="flex items-center justify-center gap-3 mb-3">
          <div
            class="w-12 h-12 rounded-xl flex items-center justify-center text-2xl"
            style="background: linear-gradient(135deg, #18a058, #2080f0)"
          >
            🏠
          </div>
          <h1 class="text-3xl font-bold" :style="{ color: appStore.isDark ? '#fff' : '#1a1a1a' }">
            Home Guardian
          </h1>
        </div>
        <p :style="{ color: appStore.isDark ? 'rgba(255,255,255,0.45)' : 'rgba(0,0,0,0.45)' }">
          智能家居守护平台
        </p>
      </div>

      <NCard
        :style="{
          backgroundColor: appStore.cardBg,
          backdropFilter: 'blur(12px)',
          borderRadius: '12px',
          border: appStore.isDark ? '1px solid rgba(255,255,255,0.06)' : '1px solid rgba(0,0,0,0.08)',
        }"
      >
        <NForm ref="formRef" :model="form" :rules="rules" size="large">
          <NFormItem path="username" label="用户名">
            <NInput
              v-model:value="form.username"
              placeholder="请输入用户名"
              @keyup.enter="handleLogin"
            />
          </NFormItem>
          <NFormItem path="password" label="密码">
            <NInput
              v-model:value="form.password"
              type="password"
              show-password-on="click"
              placeholder="请输入密码"
              @keyup.enter="handleLogin"
            />
          </NFormItem>
          <NButton
            type="primary"
            block
            strong
            :loading="loading"
            @click="handleLogin"
            class="mt-2"
          >
            登 录
          </NButton>
        </NForm>
      </NCard>
    </div>
  </div>
</template>
